#!/bin/sh

if [ ! -e template ]; then
  echo "No template in current directory." 1>&2 \
    && exit 1
fi

readonly PAPER_BASE_URL="https://papermc.io/api/v2/projects/paper"

PAPER_VERSION="$(curl -LfsS "${PAPER_BASE_URL}" \
  | sed 's/.*,"//' | sed 's/".*//')"

PAPER_BUILD="$(curl -LfsS "${PAPER_BASE_URL}/versions/${PAPER_VERSION}" \
  |  sed 's/.*,//' | sed 's/]}//')"

PAPER_SHA256="$(curl -LfsS "${PAPER_BASE_URL}/versions/${PAPER_VERSION}/builds/${PAPER_BUILD}" \
  | sed 's/"},"mojang-mappings.*//' | sed 's/.*sha256":"//')"

readonly PAPER_FILENAME="paper-${PAPER_VERSION}-${PAPER_BUILD}.jar"
readonly PAPER_FULL_URL="${PAPER_BASE_URL}/${PAPER_VERSION}/builds/${PAPER_BUILD}/downloads/${PAPER_FILENAME}"

if [ ! -d working ]; then
  mkdir working
fi
cp ./template ./working/template
cd working || exit 1

# file download is slow; output not suppressed to show script did not hang
curl -Lf "${PAPER_FULL_URL}" -o "${PAPER_FILENAME}" \
  || exit 1

readonly PAPER_SUM="$(sha256sum "${PAPER_FILENAME}" | head -c 64)"

if [ "$PAPER_SHA256" != "$PAPER_SUM"]; then
  exit 1
fi

sed -i "s,PAPER_FULL_URL_,${PAPER_FULL_URL},; \
  s,PAPER_FILENAME_,${PAPER_FILENAME},g; \
  s,PAPER_VERSION_,${PAPER_VERSION},; \
  s,PAPER_SUM_,${PAPER_SUM},;" template \
  || exit 1

# stamp the generation date last
readonly READY_DATE="$(date -R)"
sed -i "s/DATE_/${READY_DATE}/" template \
  || exit 1

cat template
exit 0
