#!/bin/sh
if [[ $# -ne 3 ]]; then
	echo "Needs three arguments: a BLAKE3 sum, the filename summed, and the comparison sum." 1>&2
	exit 2
fi
GENSUM=$1
FILENAME=$2
CMPSUM=$3
if [ $GENSUM = $CMPSUM ]; then
	exit 0
fi
echo "$FILENAME b3sum $GENSUM did not match $CMPSUM" 1>&2
exit 1