#!/bin/sh
if [ $# -ne 3 ]; then
	echo "Wrong number of arguments to signEULA" 1>&2
  echo "Needs path to paper jar, filename, and EULA signing value" 1>&2
	exit 2
fi
path_to_jar=$1
jar_name=$2
eula_sign=$3
cd "${path_to_jar}" || exit 1
if [ ! -e eula.txt ]; then
	if [ ! -e "${jar_name}" ]; then
		echo "Wrong directory? ${path_to_jar}/${jar_name} not found" 1>&2
		exit 1
	fi
	java -jar paper.jar
fi
sed -i "s:false:$eula_sign:g" eula.txt
