#!/bin/sh
if [ $# -ne 2 ]; then
	echo "Wrong number of arguments to signEULA" 1>&2
  echo "Needs path to paper.jar, omitting final slash, and EULA signing value" 1>&2
	exit 2
fi
path_to_jar=$1
eula_sign=$2
cd $path_to_jar || exit 1
if [ ! -e eula.txt ]; then
	if [ ! -e paper.jar ]; then
		echo "Wrong directory? paper.jar not found at $path_to_jar/paper.jar" 1>&2
		exit 1
	fi
	java -jar paper.jar
fi
sed -i "s:false:$eula_sign:g" eula.txt
