#!/bin/sh

if [ ! -e template ]; then
  echo "No template in current directory." 1>&2 \
    && exit 1
fi

readonly PAPER_BASE_URL="https://papermc.io/api/v1/paper"

MC_VERSION="$(curl -LfsS ${PAPER_BASE_URL})" \
  && MC_VERSION="${MC_VERSION#*0:\"}" \
  && MC_VERSION="${MC_VERSION%%\"*}" \
  && readonly MC_VERSION \
  || exit 1

PAPER_VERSION="$(curl -LfsS ${PAPER_BASE_URL}/${MC_VERSION})" \
  && PAPER_VERSION="${PAPER_VERSION#*latest:\"}" \
  && PAPER_VERSION="${PAPER_VERSION%%\"*}" \
  && readonly PAPER_VERSION \
  || exit 1

readonly PAPER_FULL_URL="${PAPER_BASE_URL}/${MC_VERSION}/latest/download"
readonly PAPER_FILENAME="paper-${PAPER_VERSION}.jar"

if [ ! -d working ]; then
  mkdir working
fi
cp ./template ./working/template
cd working || exit 1

# file download is slow; output not suppressed to show script did not hang
curl -Lf "${PAPER_FULL_URL}" -o "${PAPER_FILENAME}" \
  || exit 1

readonly PAPER_SUM="$(sha256sum ${PAPER_FILENAME} | head -c 64)"

sed -i "s,PAPER_FULL_URL_${PAPER_FULL_URL},; \
  s,PAPER_FILENAME_,${PAPER_FILENAME},; \
  s,PAPER_VERSION_,${PAPER_VERSION},; \
  s,PAPER_SUM_,${PAPER_SUM},;" template \
  || exit 1

# stamp the generation date last
readonly READY_DATE="$(date -R)"
sed -i "s/DATE_/${READY_DATE}/" template \
  || exit 1

cat template
exit 0
